### ISSUE TITLE
direct Wikipedia API access feature 

### ISSUE THREAD

**Issue by Mehdi-RZ** [Mehdi-RZ/WikipediaSpeedRun#4]
### Description :
- since i was using the WikipediaAPI library with threads , they were working fine , untill they an error started occuring ( no changes were made to the code):  **"Exception json.decoder.JSONDecodeError"**
### To-Do : 
- [ ]  test the Direct access to the Wikipedia API (without using a library this time)
- [ ]  test it with Multi threading
- [ ]  improve threading process , to stop request abuse
